Onsenを削除して、録音と同期が問題ない程度の整合性をとりました。
sun-yryr/Rec-adio pull request #114
Opened 2023-01-13 12:20 UTC by chottokun

・Onsenの仕様変更、番組収得できず。機能削除。
・rcloneの同期元ディレクトリを録音フォルダを対象に
一週間ほど動作させてradiko, agqrの録音に問題ないのを確認しました。

v4作成されているようですが、v3も動きがあったので、単に今動いているものを共有しします。

ど素人のため、PRするか悩んだのですが・・・
感謝して使わせてもらってます。

2023-01-15 10:48 UTC, sun-yryr commented
音泉さん仕様変更されたんですね、、、
PRありがとうございます。こちらでも確認してからマージさせていただきます！

2023-01-15 13:07 UTC, chottokun commented
・とりあえず、音泉を録音対象から外した
・rcloneで録音のタイミングによって、録音途中のファイルをコピーしようとしてエラーが発生していた。
のを解消しただけです。不明なところありましたら、整理します。よろしくお願いいたします。

2023-01-27 02:30 UTC, sun-yryr requested changes

2023-01-27 02:30 UTC, sun-yryr commented on run.py
>  def main_onsen_hibiki():
gitignoreのコメントを出してしまったので、よければこっちもお願いしたいです。

main_hibikiに処理を切り出しているので、元々のmain_onsen_hibikiからhibikiの処理を抜いてmain_onsenに修正して欲しいです。（コメントアウトは外してもらって大丈夫です）

2023-01-27 02:30 UTC, sun-yryr commented on .gitignore
> +.git
@chottokun 多分 `.git` 必要ないので削除お願いします！

2023-01-27 12:27 UTC, chottokun commented on run.py
>  def main_onsen_hibiki():
了解です！

2023-01-30 14:01 UTC, chottokun commented
こんな感じでいかがでしょうか。動作する最低限ですが・・・。

2023-03-24 05:44 UTC, sun-yryr commented
ありがとうございました！

2023-03-24 05:44 UTC, merged